### ISSUE TITLE
eqsans_prepare failing

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#167]
Executing the following script:
```
from ornl.sans.sns import eqsans
ws = eqsans.prepare_data("EQSANS_104088",
                         detector_offset=0,
                         sample_offset=0,
                         bin_width=0.1,
                         low_tof_clip=0, high_tof_clip=0,
                         x_center=96.29, y_center=126.15,
                         output_workspace='raw_data')
```

produces this output:
```
Traceback (most recent call last):
  File "user_testing.py", line 15, in <module>
    output_workspace='raw_data')
  File "/SNS/users/m2d/anaconda3/envs/py36/lib/python3.6/site-packages/ornl-0+untagged.725.ga3b93d4.dirty-py3.6.egg/ornl/sans/sns/eqsans/api.py", line 102, in prepare_data
    apply_mask(output_workspace, panel=panel, mask=mask, **btp)
  File "/SNS/users/m2d/anaconda3/envs/py36/lib/python3.6/site-packages/ornl-0+untagged.725.ga3b93d4.dirty-py3.6.egg/ornl/sans/sns/eqsans/mask.py", line 34, in apply_mask
    output_workspace=output_workspace, **btp)
  File "/SNS/users/m2d/anaconda3/envs/py36/lib/python3.6/site-packages/ornl-0+untagged.725.ga3b93d4.dirty-py3.6.egg/ornl/sans/mask_utils.py", line 56, in apply_mask
    instrument = w.getInstrument().getName()
AttributeError: 'str' object has no attribute 'getInstrument'
```

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/121).
