### ISSUE TITLE
save_ascii_1D fails on masked arrays

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#207]
When trying to save a masked array, I get 
```
Traceback (most recent call last):
  File "eqsans_reduction.py", line 151, in <module>
    outfile)
  File "/home/3y9/SANS/sans-backend/ornl/sans/save_ascii.py", line 25, in save_ascii_1D
    f.write('{:.6f}\t'.format(intensity[i]))
TypeError: unsupported format string passed to MaskedConstant.__format__
```

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/161).
