### ISSUE TITLE
I'm getting this error when trying to reduce BIOSANS data from Shaman

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#335]
```
Traceback (most recent call last):
  File "/SNS/software/miniconda2/envs/sans/bin/biosans_reduction.py", line 123, in <module>
    overwrite_instrument=True, output_workspace=uwd())
  File "/SNS/software/miniconda2/envs/sans/lib/python3.6/site-packages/drtsans/mono/load.py", line 52, in load_events
    LoadEventNexus(Filename=str(run), OutputWorkspace=output_workspace, LoadMonitors=True, **kwargs)
  File "/SNS/software/miniconda2/envs/sans/lib/python3.6/site-packages/mantid/simpleapi.py", line 1130, in algorithm_wrapper
    set_properties(algm, *args, **final_keywords)
  File "/SNS/software/miniconda2/envs/sans/lib/python3.6/site-packages/mantid/simpleapi.py", line 1067, in set_properties
    do_set_property(key, value)
  File "/SNS/software/miniconda2/envs/sans/lib/python3.6/site-packages/mantid/simpleapi.py", line 1050, in do_set_property
    alg_object.setProperty(key, new_value)
RuntimeError: Failed to find an instrument with this name in any facility: '' - search object
```

This was working but now it looks like it no longer accepts a run number for `runNumber` but requires a full path to the file?

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/288).
