### ISSUE TITLE
parsing for log binning

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#527]
1. json input:

{"instrumentName": "EQSANS", "iptsNumber": "", "runNumber": "111524", "thickness": "1", "outputFilename": "sPorsil_4m2o5afs_qbin20_falseevendecade", "transmission": {"runNumber": "111522", "value": ""}, "background": {"runNumber": "111523", "transmission": {"runNumber": "111521", "value": ""}}, "beamCenter": {"runNumber": "111520"}, "empty": {"runNumber": "111520"}, "configuration": {"outputDir": "/SNS/EQSANS/shared/codereview/acceptance/ccd/output_after0313/", "sampleApertureSize": "10", "useMaskFileName": true, "maskFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/mask_4m_general.nxs", "useDefaultMask": true, "normalization": "Total charge", "fluxMonitorRatioFile": "/SNS/EQSANS/IPTS-24769/shared/EQSANS_110943.out", "beamFluxFileName": "/SNS/EQSANS/shared/instrument_configuration/bl6_flux_at_sample", "useDarkFileName": true, "darkFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/EQSANS_105680.nxs.h5", "useSensitivityFileName": true, "sensitivityFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/Sensitivity_patched_thinPMMA_4m_108772.nxs", "absoluteScaleMethod": "standard", "StandardAbsoluteScale": "5.18325", "useSampleOffset": true, "sampleOffset": "314.5", "useDetectorOffset": true, "detectorOffset": "0", "useSolidAngleCorrection": true, "useThetaDepTransCorrection": true, "mmRadiusForTransmission": "25.0", "numQxQyBins": "80", "1DQbinType": "scalar", "QbinType": "log", "numQBins": "20", "LogQBinsPerDecade": "", "LogQBinsDecadeCenter": false, "LogQBinsEvenDecade": false, "WedgeMinAngles": "-30, 60", "WedgeMaxAngles": "30, 120", "AnnularAngleBin": "5", "Qmin": "", "Qmax": "", "useErrorWeighting": false, "useTOFcuts": false, "TOFmin": "500.0", "TOFmax": "2000.0", "useMaskBackTubes": false, "wavelengthStepType": "constant lambda", "wavelengthStep": "0.1", "pixel_size_x": "", "pixel_size_y": "", "timeslice": false, "timesliceinterval": 300.0, "usesliceidxassuffix": true, "logslice": false, "logslicename": "", "logsliceinterval": 10.0, "fluxmonitorratiofile": "/SNS/EQSANS/IPTS-24769/shared/EQSANS_110943.out", "usedarkFileName": true, "wavelenStep": 0.1}}

note that numQBins is 20. LogQBinsEvenDecade = false

Issue: The reduction consideres numQBins as num_bin_decade. However, number of data points per decade is almost 40. Please see Iq.dat below:
```
> mod_q intensity error delta_mod_q
> 0.004373 470.731435 18.738884 0.001023
> 0.004627 454.014296 10.031910 0.001048
> 0.004897 460.681217 6.903945 0.001062
> 0.005182 450.214558 4.603101 0.001080
> 0.005484 430.813840 3.504916 0.001101
> 0.005804 415.314865 2.824060 0.001121
> 0.006142 406.972810 2.423304 0.001131
> 0.006499 397.065449 2.170639 0.001139
> 0.006878 385.750569 2.014795 0.001136
> 0.007279 372.318058 1.820678 0.001138
> 0.007703 361.094473 1.654146 0.001138
> 0.008152 348.168020 1.533136 0.001139
> 0.008626 334.048063 1.399619 0.001140
> 0.009129 326.819555 1.298948 0.001140
> 0.009661 313.124357 1.195604 0.001139
> 
> 0.010223 303.617397 1.102242 0.001140
> 0.010819 291.121269 1.009685 0.001140
> 0.011449 278.329862 0.922748 0.001140
> 0.012116 264.693931 0.842056 0.001141
> 0.012822 253.901168 0.779324 0.001140
> 0.013569 238.804421 0.701794 0.001141
> 0.014360 224.180633 0.638408 0.001141
> 0.015196 211.585707 0.581148 0.001141
> 0.016081 195.867987 0.523544 0.001141
> 0.017018 181.840722 0.471066 0.001141
> 0.018010 167.568321 0.423225 0.001141
> 0.019059 153.746188 0.380957 0.001141
> 0.020169 139.295569 0.338222 0.001141
> 0.021344 125.198764 0.300070 0.001142
> 0.022587 112.047173 0.266363 0.001142
> 0.023903 99.324295 0.235136 0.001142
> 0.025296 87.586579 0.207448 0.001142
> 0.026769 76.116521 0.180785 0.001142
> 0.028329 66.226615 0.158367 0.001143
> 0.029979 56.722297 0.137370 0.001143
> 0.031725 48.492694 0.120359 0.001143
> 0.033573 40.913864 0.104827 0.001144
> 0.035529 34.182430 0.090763 0.001144
> 0.037599 28.507870 0.079027 0.001145
> 0.039789 23.551316 0.068878 0.001145
> 0.042107 19.094156 0.059892 0.001146
> 0.044560 15.408233 0.052512 0.001147
> 0.047156 12.416847 0.046609 0.001147
> 0.049903 9.818160 0.041372 0.001148
> 0.052810 7.734576 0.037136 0.001148
> 0.055887 6.101157 0.033535 0.001151
> 0.059142 4.711987 0.030710 0.001156
> 0.062588 3.693676 0.028992 0.001161
> 0.066234 2.886926 0.027483 0.001167
> 0.070092 2.282286 0.026594 0.001175
> 0.074175 1.780216 0.026204 0.001183
> 0.078496 1.398761 0.025870 0.001197
> 0.083069 1.111530 0.026319 0.001212
> 0.087908 0.885468 0.027612 0.001228
> 0.093029 0.694293 0.028809 0.001251
> 0.098449 0.572822 0.030853 0.001278
> 0.104184 0.459418 0.035198 0.001306
> 
> 0.110253 0.379077 0.043995 0.001338
> 0.116676 0.280556 0.068267 0.001367
> 0.123473 0.146841 0.165890 0.001394
```

2. Next, I set, numQBins is 20. LogQBinsEvenDecade = true, here is json:

{"instrumentName": "EQSANS", "iptsNumber": "", "runNumber": "111524", "thickness": "1", "outputFilename": "sPorsil_4m2o5afs_qbin20_trueevendecade", "transmission": {"runNumber": "111522", "value": ""}, "background": {"runNumber": "111523", "transmission": {"runNumber": "111521", "value": ""}}, "beamCenter": {"runNumber": "111520"}, "empty": {"runNumber": "111520"}, "configuration": {"outputDir": "/SNS/EQSANS/shared/codereview/acceptance/ccd/output_after0313/", "sampleApertureSize": "10", "useMaskFileName": true, "maskFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/mask_4m_general.nxs", "useDefaultMask": true, "normalization": "Total charge", "fluxMonitorRatioFile": "/SNS/EQSANS/IPTS-24769/shared/EQSANS_110943.out", "beamFluxFileName": "/SNS/EQSANS/shared/instrument_configuration/bl6_flux_at_sample", "useDarkFileName": true, "darkFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/EQSANS_105680.nxs.h5", "useSensitivityFileName": true, "sensitivityFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/Sensitivity_patched_thinPMMA_4m_108772.nxs", "absoluteScaleMethod": "standard", "StandardAbsoluteScale": "5.18325", "useSampleOffset": true, "sampleOffset": "314.5", "useDetectorOffset": true, "detectorOffset": "0", "useSolidAngleCorrection": true, "useThetaDepTransCorrection": true, "mmRadiusForTransmission": "25.0", "numQxQyBins": "80", "1DQbinType": "scalar", "QbinType": "log", "numQBins": "20", "LogQBinsPerDecade": "", "LogQBinsDecadeCenter": false, "LogQBinsEvenDecade": true, "WedgeMinAngles": "-30, 60", "WedgeMaxAngles": "30, 120", "AnnularAngleBin": "5", "Qmin": "", "Qmax": "", "useErrorWeighting": false, "useTOFcuts": false, "TOFmin": "500.0", "TOFmax": "2000.0", "useMaskBackTubes": false, "wavelengthStepType": "constant lambda", "wavelengthStep": "0.1", "pixel_size_x": "", "pixel_size_y": "", "timeslice": false, "timesliceinterval": 300.0, "usesliceidxassuffix": true, "logslice": false, "logslicename": "", "logsliceinterval": 10.0, "fluxmonitorratiofile": "/SNS/EQSANS/IPTS-24769/shared/EQSANS_110943.out", "usedarkFileName": true, "wavelenStep": 0.1}}

Issue 1: output data (Iq.dat) cannot be loaded from mantidplot, because there are empty columns as below:
```
> [ccd@analysis-node11 output_after0313]$ cat sPorsil_4m2o5afs_qbin20_trueevendecade_frame_0_Iq.dat
> mod_q intensity error delta_mod_q
> 0.001059   
> 0.001189   
> 0.001334   
> 0.001496   
> 0.001679   
> 0.001884   
> 0.002113   
> 0.002371   
> 0.002661   
> 0.002985   
> 0.003350   
> 0.003758   
> 0.004217 476.905071 21.632260 0.001020
> 0.004732 457.717929 5.778755 0.001058
> 0.005309 438.567826 2.830513 0.001091
> 0.005957 411.634530 1.829726 0.001126
> 0.006683 390.708521 1.461477 0.001137
> 0.007499 365.739629 1.210332 0.001138
> 0.008414 339.605126 1.018556 0.001139
> 0.009441 319.101808 0.864662 0.001140
> 0.010593 294.929344 0.729661 0.001140
> 0.011885 268.784499 0.608526 0.001140
> 0.013335 242.778908 0.506408 0.001141
> 0.014962 213.527158 0.415387 0.001141
> 0.016788 184.785598 0.338012 0.001141
> 0.018836 155.732661 0.271334 0.001141
> 0.021135 126.990591 0.214032 0.001141
> 0.023714 100.582263 0.167160 0.001142
> 0.026607 77.013219 0.128204 0.001142
> 0.029854 57.099928 0.097158 0.001143
> 0.033497 40.973099 0.073529 0.001144
> 0.037584 28.366842 0.055277 0.001145
> 0.042170 18.873337 0.041692 0.001146
> 0.047315 12.170492 0.032318 0.001147
> 0.053088 7.527089 0.025684 0.001149
> 0.059566 4.576900 0.021416 0.001157
> 0.066834 2.791006 0.019184 0.001169
> 0.074989 1.714858 0.018351 0.001186
> 0.084140 1.068737 0.018738 0.001215
> 0.094406 0.680107 0.020849 0.001256
> 0.105925 0.447721 0.026506 0.001311
> 0.118850 0.281102 0.056464 0.001366
> 0.133352 -0.000027 1.254762 0.001416
> 0.149624   
> 0.167880   
> 0.188365   
> 0.211349   
> 0.237137   
> 0.266073   
> 0.298538   
> 0.334965   
> 0.375837   
> 0.421697   
> 0.473151   
> 0.530884   
> 0.595662   
> 0.668344   
> 0.749894   
> 0.841395   
> 0.944061  
```
-Issue 2:  number of bins per decade is now 20. Somehow the number of bins per decade is differently estimated depending on the values of LogQBinsEvenDecade.

3. with explicitly define  "numQBins": "", "LogQBinsPerDecade": 20, see json below

{"instrumentName": "EQSANS", "iptsNumber": "", "runNumber": "111524", "thickness": "1", "outputFilename": "sPorsil_4m2o5afs_binperdecade20_trueevendecade", "transmission": {"runNumber": "111522", "value": ""}, "background": {"runNumber": "111523", "transmission": {"runNumber": "111521", "value": ""}}, "beamCenter": {"runNumber": "111520"}, "empty": {"runNumber": "111520"}, "configuration": {"outputDir": "/SNS/EQSANS/shared/codereview/acceptance/ccd/output_after0313/", "sampleApertureSize": "10", "useMaskFileName": true, "maskFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/mask_4m_general.nxs", "useDefaultMask": true, "normalization": "Total charge", "fluxMonitorRatioFile": "/SNS/EQSANS/IPTS-24769/shared/EQSANS_110943.out", "beamFluxFileName": "/SNS/EQSANS/shared/instrument_configuration/bl6_flux_at_sample", "useDarkFileName": true, "darkFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/EQSANS_105680.nxs.h5", "useSensitivityFileName": true, "sensitivityFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/Sensitivity_patched_thinPMMA_4m_108772.nxs", "absoluteScaleMethod": "standard", "StandardAbsoluteScale": "5.18325", "useSampleOffset": true, "sampleOffset": "314.5", "useDetectorOffset": true, "detectorOffset": "0", "useSolidAngleCorrection": true, "useThetaDepTransCorrection": true, "mmRadiusForTransmission": "25.0", "numQxQyBins": "80", "1DQbinType": "scalar", "QbinType": "log", "numQBins": "", "LogQBinsPerDecade": 20, "LogQBinsDecadeCenter": false, "LogQBinsEvenDecade": true, "WedgeMinAngles": "-30, 60", "WedgeMaxAngles": "30, 120", "AnnularAngleBin": "5", "Qmin": "", "Qmax": "", "useErrorWeighting": false, "useTOFcuts": false, "TOFmin": "500.0", "TOFmax": "2000.0", "useMaskBackTubes": false, "wavelengthStepType": "constant lambda", "wavelengthStep": "0.1", "pixel_size_x": "", "pixel_size_y": "", "timeslice": false, "timesliceinterval": 300.0, "usesliceidxassuffix": true, "logslice": false, "logslicename": "", "logsliceinterval": 10.0, "fluxmonitorratiofile": "/SNS/EQSANS/IPTS-24769/shared/EQSANS_110943.out", "usedarkFileName": true, "wavelenStep": 0.1}}

Issue: Error 
[ccd@analysis-node11 output_after0313]$ cat sPorsil_4m2o5afs_binperdecade20_trueevendecade.err
Traceback (most recent call last):
  File "/SNS/users/ccd/eqsanstools/eqsans_reduction.py", line 31, in <module>
    out=reduce_single_configuration(loaded, reduction_input)
  File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/tof/eqsans/api.py", line 739, in reduce_single_configuration
    error_weighted=weighted_errors)
  File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/iq.py", line 219, in bin_all
    bins_1d = determine_1d_log_bins(qmin, qmax, n_bins_per_decade=n1dbins, even_decade=even_decade)
  File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/determine_bins.py", line 109, in determine_1d_log_bins
    'and they must be positive integers'.format(n_bins_per_decade, n_bins))
RuntimeError: n_bins_per_decade (None) and n_bins (None) cannot be both specified or not specified.and they must be positive integers

Note 1. bin_all function now takes all the needed parameters, but 
```python
        if log_scale:
            bins_1d = determine_1d_log_bins(qmin, qmax, n_bins_per_decade=n1dbins, even_decade=even_decade)
        else:
            bins_1d = determine_1d_linear_bins(qmin, qmax, n1dbins)
```
they are not transferred to determine_1d_log_bins properly.

Note 2. There needs to be a logic to decide what to do when both numqbins and logqbinsperdecades are given and also when one of them is given.

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/481).
