### ISSUE TITLE
looking for emptyTrans instead of empty

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#528]
current version of eqsan json file looks like this (from this repository)
```
{
  "instrumentName": "EQSANS",
  "iptsNumber": "24769",
  "runNumber": "112300",
  "thickness": "1",
  "outputFilename": "EQSANS_112300",
  "transmission": {
    "runNumber": "112297",
    "value": ""
  },
  "background": {
    "runNumber": "112299",
    "transmission": {
      "runNumber": "112296",
      "value": ""
    }
  },
  "beamCenter": {
    "runNumber": "112295"
  },
  "empty": {
    "runNumber": "112295"
  },
  "configuration": {
    "outputDir": "/tmp/shared/shaman/",
    "sampleApertureSize": "10",
    "useMaskFileName": true,
    "maskFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/mask_beamstop60_4m.nxs",
    "useDefaultMask": true,
    "normalization": "Total charge",
    "fluxMonitorRatioFile": "/SNS/EQSANS/IPTS-24769/shared/EQSANS_110943.out",
    "beamFluxFileName": "/SNS/EQSANS/shared/instrument_configuration/bl6_flux_at_sample",
    "useDarkFileName": false,
    "darkFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/EQSANS_108764.nxs.h5",
    "useSensitivityFileName": false,
    "sensitivityFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2019B_mp/Sensitivity_patched_thinPMMA_4m_108772.nxs",
    "absoluteScaleMethod": "standard",
    "StandardAbsoluteScale": "1",
    "useSampleOffset": true,
    "sampleOffset": "314.5",
    "useDetectorOffset": true,
    "detectorOffset": "0",
    "useSolidAngleCorrection": true,
    "useThetaDepTransCorrection": true,
    "mmRadiusForTransmission": "25.0",
    "numQxQyBins": "80",
    "1DQbinType": "scalar",
    "QbinType": "linear",
    "numQBins": "120",
    "LogQBinsPerDecade": "",
    "LogQBinsDecadeCenter": false,
    "LogQBinsEvenDecade": false,
    "WedgeMinAngles": "-30, 60",
    "WedgeMaxAngles": "30, 120",
    "AnnularAngleBin": "5",
    "Qmin": "",
    "Qmax": "",
    "useErrorWeighting": false,
    "useTOFcuts": false,
    "TOFmin": "500.0",
    "TOFmax": "2000.0",
    "useMaskBackTubes": false,
    "wavelengthStepType": "constant lambda",
    "wavelengthStep": "0.1",
    "pixel_size_x": "",
    "pixel_size_y": "",
    "timeslice": false,
    "timesliceinterval": 300.0,
    "usesliceidxassuffix": true,
    "logslice": false,
    "logslicename": "",
    "logsliceinterval": 10.0,
    "fluxmonitorratiofile": "/SNS/EQSANS/IPTS-24769/shared/EQSANS_110943.out",
    "usedarkFileName": true,
    "wavelenStep": 0.1
  }
}

```

there is not item called "emptyTrans"

when I run
```
python eqsans_reduction.py myjson.json
```

I get errors saying it's looking for this "emptyTrans"

Python-[Notice] drtsans version: 0+unknown
Traceback (most recent call last):
  File "../eqsans_reduction.py", line 33, in <module>
    loaded = load_all_files(reduction_input)
  File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/settings.py", line 47, in wrapper
    res = func(*args, **kwargs)
  File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/mono/gpsans/api.py", line 53, in load_all_files
    empty = reduction_input["emptyTrans"]["runNumber"]
KeyError: 'emptyTrans'

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/482).
