### ISSUE TITLE
Error in EQSANS reduction when calculating the transmission

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#602]
(reported by Changwoo)

> This is the json file:  
> {"schemaStamp": "2020-04-30T18:05:55.993903", "instrumentName": "EQSANS", "iptsNumber": "24876", "sample": {"runNumber": "110794", "thickness": 1, "transmission": {"runNumber": "110793", "value": ""}}, "background": {"runNumber": "110792", "transmission": {"runNumber": "110791", "value": ""}}, "emptyTransmission": {"runNumber": "110791", "value": null}, "beamCenter": {"runNumber": "110791"}, "outputFileName": "nd_FN8041_700C", "configuration": {"outputDir": "/SNS/EQSANS/shared/codereview/acceptance/ccd/output_0430/", "useTimeSlice": false, "timeSliceInterval": 300, "useLogSlice": true, "logSliceName": "BL6:SE:NDBLS:CH1:PV", "logSliceInterval": 200, "useTOFcuts": false, "cutTOFmin": 500.0, "cutTOFmax": 1500.0, "wavelengthStep": 0.1, "wavelengthStepType": "constant Delta lambda", "sampleOffset": "314.5", "useDetectorOffset": true, "detectorOffset": "80", "sampleApertureSize": 10, "sourceApertureDiameter": null, "usePixelCalibration": null, "maskFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/mask_4m_extended.nxs", "useDefaultMask": true, "defaultMask": null, "useMaskBackTubes": false, "darkFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/EQSANS_113569.nxs.h5", "normalization": null, "fluxMonitorRatioFile": null, "beamFluxFileName": "/SNS/EQSANS/shared/instrument_configuration/bl6_flux_at_sample", "sensitivityFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/Sensitivity_patched_thinPMMA_4m_113512_mantid.nxs", "useSolidAngleCorrection": true, "useThetaDepTransCorrection": true, "mmRadiusForTransmission": 25, "absoluteScaleMethod": "standard", "StandardAbsoluteScale": 1, "numQxQyBins": 80, "1DQbinType": "scalar", "QbinType": "log", "numQBins": 10, "LogQBinsPerDecade": null, "useLogQBinsDecadeCenter": false, "useLogQBinsEvenDecade": false, "WedgeMinAngles": "-30, 60", "WedgeMaxAngles": "30, 120", "autoWedgeQmin": null, "autoWedgeQmax": null, "autoWedgeQdelta": null, "autoWedgeAzimuthalDelta": null, "autoWedgePeakWidth": null, "autoWedgeBackgroundWidth": null, "autoWedgeSignalToNoiseMin": 2.0, "AnnularAngleBin": 5.0, "Qmin": null, "Qmax": null, "useErrorWeighting": null, "smearingPixelSizeX": null, "smearingPixelSizeY": null, "useSubpixels": null, "subpixelsX": null, "subpixelsY": null, "useSliceIDxAsSuffix": false}, "dataDirectories": "/SNS/EQSANS/shared/codereview/acceptance/ccd/output_0430/"}
>   
>   
> Error happens at this part of the output:  
>   
> Done loading  
> FILE PATH, FILE SIZE:  
> /SNS/EQSANS/IPTS-23495/nexus/EQSANS_110791.nxs.h5, 7.61 MiB  
> /SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/Sensitivity_patched_thinPMMA_4m_113512_mantid.nxs, 57.17 MiB  
> /SNS/EQSANS/IPTS-23495/nexus/EQSANS_110793.nxs.h5, 13.13 MiB  
> /SNS/EQSANS/IPTS-23495/nexus/EQSANS_110794.nxs.h5, 1318.81 MiB  
> /SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/EQSANS_113569.nxs.h5, 545.60 MiB  
> /SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/mask_4m_extended.nxs, 21.32 MiB  
> /SNS/EQSANS/IPTS-23495/nexus/EQSANS_110792.nxs.h5, 74.74 MiB  
> TOTAL:  2038.37 MB  
> Background transmission = 1.0000000000000069  
> Sample transmission = 2.261612169861952  
>   
>   
> By the way, those transmissions do not make any sense..    
> This is the error message:  
>   
> Traceback (most recent call last):  
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/mantid/simpleapi.py", line 1136, in algorithm_wrapper  
>     algm.execute()  
> RuntimeError: Some invalid Properties found  
>   
> During handling of the above exception, another exception occurred:  
>   
> Traceback (most recent call last):  
>   File "/SNS/EQSANS/shared/script/eqsanstools/eqsans_reduction.py", line 40, in <module>
>     reduce_eqsans_configuration(reduction_input)  
>   File "/SNS/EQSANS/shared/script/eqsanstools/eqsans_reduction.py", line 21, in reduce_eqsans_configuration
>     out = reduce_single_configuration(loaded, input_config)  
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/tof/eqsans/api.py", line 674, in reduce_single_configuration  
>     keep_processed_workspaces=False)  
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/tof/eqsans/api.py", line 475, in process_single_configuration  
>     output_workspace=output_workspace)  
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/transmission.py", line 168, in apply_transmission_correction  
>     ApplyTransmissionCorrection(**kwargs)  
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/mantid/simpleapi.py", line 1140, in algorithm_wrapper  
>     _check_mandatory_args(name, algm, e, *args, **kwargs)  
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/mantid/simpleapi.py", line 830, in _check_mandatory_args  
>     raise RuntimeError(str(error))  
> RuntimeError: Some invalid Properties found  
> 
> 
> 
> Thank you very much,
> Changwoo

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/556).
