### ISSUE TITLE
EQSANS reduction error for narrow transmitted wavelength band

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#627]
Reported by Gergely

[EQSANS_111274_sCarbon.json](/uploads/76786e51c94a65da8fe58c910c976fff/EQSANS_111274_sCarbon.json)

> Dear All,
> 
> Please find here an error which we found when analyzing some data in IPTS-24648. This is the one I mentioned in the morning status meeting. We think the data is special in the sense that due to a special chopper setup a narrow wavelength band was hitting the sample. The reduction fails with drtsans, but interestingly not with mantid.  We consider that this issue would be good to be addressed, but it has low priority.
> 
> The script producing the error is:
> /SNS/snfs1/instruments/EQSANS/shared/codereview/acceptance/4gn_final/ipts24648/
> reduce_sCarbon_ipts24648.py
> 
> The samples are: runnumbers: 111274,111275,111276,111277,111278,111279,111280,111281,111282,111283,111284
> EB = 111273
> 
> The errormessage is:
> Traceback (most recent call last):
>   File "/SNS/EQSANS/shared/script/eqsanstools/eqsans_reduction.py", line 40, in <module>
>     reduce_eqsans_configuration(reduction_input)
>   File "/SNS/EQSANS/shared/script/eqsanstools/eqsans_reduction.py", line 21, in reduce_eqsans_configuration
>     out = reduce_single_configuration(loaded, input_config)
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/tof/eqsans/api.py", line 736, in reduce_single_configuration
>     error_weighted=weighted_errors)
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/iq.py", line 202, in bin_all
>     method=method)
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/iq.py", line 629, in bin_intensity_into_q2d
>     check_iq_for_binning(i_of_q)
>   File "/SNS/software/miniconda2/envs/sans-dev/lib/python3.6/site-packages/drtsans/iq.py", line 56, in check_iq_for_binning
>     raise RuntimeError('Input I(Q) for binning does not meet assumption:\n{}'.format(error_message))
> RuntimeError: Input I(Q) for binning does not meet assumption:
> Intensity error has zero [    0     1     2 ... 81197 81198 81199]
> 
> Thank you,
> Gergely

## Report:

Sample run **EQSANS 11274**  accumulated TOF and Wavelength histograms:  
<img src="/uploads/9862bbcefe545f7ba393424e99856319/Capture.PNG" width="600">  

The chopper code of drtsans give the following wavelength bands transmitted by each of the four disk choppers (the last two are a double-chopper system)

```
(Wband(0.000, 2.071), Wband(9.346, 13.640), Wband(20.756, 25.210), Wband(32.167, 35.000))
(Wband(0.000, 1.748), Wband(5.915, 10.202), Wband(14.284, 18.656), Wband(22.654, 27.111), Wband(31.023, 35.000))
(Wband(0.000, 3.331), Wband(5.789, 10.274), Wband(12.676, 17.218), Wband(19.562, 24.161), Wband(26.448, 31.105), Wband(33.334, 35.000))
(Wband(0.000, 0.561), Wband(3.040, 7.496), Wband(9.918, 14.431), Wband(16.796, 21.366), Wband(23.674, 28.302), Wband(30.552, 35.000))
```

Thus the chopper system only transmits the following bands (according to drtsans code)

```
(Wband(0.000, 0.561), Wband(9.918, 10.202), Wband(23.674, 24.161), Wband(33.334, 35.000))
```

The histogram of counts versus wavelength shows almost no neutrons in the range of wavelengths given by the lead band `Wband(0.000, 0.561)`, so we end up with no neutrons when using the drtsans code.

The drtsans code relies in the chopper settings stored in the medata of run 11274 as well as supposedly constant values for [chopper apertures](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/blob/next/drtsans/tof/eqsans/chopper.py#L39), [distances to the source](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/blob/next/drtsans/tof/eqsans/chopper.py#L42), and most important, [phase offsets](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/blob/next/drtsans/tof/eqsans/chopper.py#L44).

Strangely enough, the `lambdarequest` value in the metadata of run 11274 is zero, which coincides with the minimum wavelength of the leading band `Wband(0.000, 0.561)`.

This problem could have been averted if we had:
1. Obtained the minimum TOF from the value  of `lambdarequest` (`lambdarequest` is zero, thus `min_tof` is zero)
2. Assumed the maximum TOF is `min_tof` plus one pulse period.

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/580).
