### ISSUE TITLE
Annular binning error on EQSANS

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#636]
>  Hi Jose and Mathieu,
> 
>  
> 
> I wasn’t sure whom to send this information. Just in case someone need this to look into the annular binning issue we mentioned today, I’m attaching my input and error text.
> 
>  
> 
> Thank you
> 
> Changwoo
> 
>  
> 
>  
> 
>  
> 
> INPUT:
> 
>  
> 
> {"schemaStamp": "2020-05-11T14:23:13.826010", "instrumentName": "EQSANS", "iptsNumber": "24876", "sample": {"runNumber": "108792", "thickness": 1, "transmission": {"runNumber": "108788", "value": ""}}, "background": {"runNumber": "108790", "transmission": {"runNumber": "108786", "value": ""}}, "emptyTransmission": {"runNumber": "108785", "value": null}, "beamCenter": {"runNumber": "108785"}, "outputFileName": "dev_AgBe_4m2o5a_ndrt", "configuration": {"outputDir": "/SNS/EQSANS/shared/codereview/acceptance/ccd/output_0508/", "useTimeSlice": false, "timeSliceInterval": 300, "useLogSlice": false, "logSliceName": null, "logSliceInterval": 10, "useTOFcuts": false, "cutTOFmin": 500.0, "cutTOFmax": 1500.0, "wavelengthStep": 0.1, "wavelengthStepType": "constant Delta lambda", "sampleOffset": 314.5, "useDetectorOffset": true, "detectorOffset": "80", "sampleApertureSize": 10, "sourceApertureDiameter": null, "usePixelCalibration": null, "maskFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/mask_4m_extended.nxs", "useDefaultMask": true, "defaultMask": null, "useMaskBackTubes": false, "darkFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/EQSANS_113569.nxs.h5", "normalization": "Total charge", "fluxMonitorRatioFile": null, "beamFluxFileName": "/SNS/EQSANS/shared/instrument_configuration/bl6_flux_at_sample", "sensitivityFileName": "/SNS/EQSANS/shared/NeXusFiles/EQSANS/2020A_mp/Sensitivity_patched_thinPMMA_4m_113512_mantid.nxs", "useSolidAngleCorrection": true, "useThetaDepTransCorrection": true, "mmRadiusForTransmission": 25, "absoluteScaleMethod": "standard", "StandardAbsoluteScale": 100, "numQxQyBins": 80, "1DQbinType": "annular", "QbinType": "log", "numQBins": 120, "LogQBinsPerDecade": null, "useLogQBinsDecadeCenter": false, "useLogQBinsEvenDecade": false, "WedgeMinAngles": "-30, 60", "WedgeMaxAngles": "30, 120", "autoWedgeQmin": null, "autoWedgeQmax": null, "autoWedgeQdelta": null, "autoWedgeAzimuthalDelta": null, "autoWedgePeakWidth": null, "autoWedgeBackgroundWidth": null, "autoWedgeSignalToNoiseMin": 2.0, "AnnularAngleBin": 5.0, "Qmin": null, "Qmax": null, "useErrorWeighting": null, "smearingPixelSizeX": null, "smearingPixelSizeY": null, "useSubpixels": null, "subpixelsX": null, "subpixelsY": null, "useSliceIDxAsSuffix": null}, "dataDirectories": "/SNS/EQSANS/shared/codereview/acceptance/ccd/output_0508/"}
> 
>  
> 
>  
> 
>  
> 
>  
> 
>  
> 
>  
> 
> ERROR:
> 
>  
> 
>  
> 
> Traceback (most recent call last):
> 
>   File "/SNS/EQSANS/shared/script/eqsanstools/eqsans_reduction.py", line 40, in <module>
> 
>     reduce_eqsans_configuration(reduction_input)
> 
>   File "/SNS/EQSANS/shared/script/eqsanstools/eqsans_reduction.py", line 21, in reduce_eqsans_configuration
> 
>     out = reduce_single_configuration(loaded, input_config)
> 
>   File "/SNS/software/miniconda2/envs/sans-qa/lib/python3.6/site-packages/drtsans/tof/eqsans/api.py", line 736, in reduce_single_configuration
> 
>     error_weighted=weighted_errors)
> 
>   File "/SNS/software/miniconda2/envs/sans-qa/lib/python3.6/site-packages/drtsans/iq.py", line 213, in bin_all
> 
>     binned_q1d_list.append(bin_annular_into_q1d(i_qxqy, bin_params, **kwargs))
> 
>   File "/SNS/software/miniconda2/envs/sans-qa/lib/python3.6/site-packages/drtsans/iq.py", line 425, in bin_annular_into_q1d
> 
>     intensity, error, q_array, dq_array, theta_array = _toQmodAndAzimuthal(i_of_q)
> 
>   File "/SNS/software/miniconda2/envs/sans-qa/lib/python3.6/site-packages/drtsans/iq.py", line 347, in _toQmodAndAzimuthal
> 
>     if not getDataType(data) == DataType.IQ_AZIMUTHAL:
> 
>   File "/SNS/software/miniconda2/envs/sans-qa/lib/python3.6/site-packages/drtsans/dataobjects.py", line 27, in getDataType
> 
>     raise ValueError('Do not know how to get id from: {}'.format(obj))
> 
> ValueError: Do not know how to get id from: frame(intensity=array([ 2.23078919e+00,  3.20968134e+00,  4.31403916e+00, ...,
> 
>         2.26074057e+00,  4.80090156e+00, -4.80360028e-04]), error=array([ 1.26431635,  1.45696899,  1.66989382, ...,  2.99838738,
> 
>         3.98715523, 13.20589266]), qx=array([-0.3100166 , -0.29869224, -0.28816604, ...,  0.16378076,
> 
>         0.16092625,  0.15919028]), qy=array([-0.29577058, -0.2849666 , -0.27492411, ...,  0.12985533,
> 
>         0.1275921 ,  0.12621572]), delta_qx=array([0.00630673, 0.0059251 , 0.00558209, ..., 0.00208522, 0.00203473,
> 
>        0.00185184]), delta_qy=array([0.00598162, 0.00561794, 0.00529111, ..., 0.0018344 , 0.00179232,
> 
>        0.00165906]), wavelength=array([2.63760839, 2.73760839, 2.83760839, ..., 5.63760839, 5.73760839,
> 
>        5.80017706]))

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/589).
