### ISSUE TITLE
Shaman test fails

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#659]
Error message:

```
Traceback (most recent call last):
  File "/SNS/users/pf9/code/drt-sans/scripts/biosans_reduction.py", line 23, in <module>
    reduction_input = validate_reduction_parameters(reduction_input)
  File "/SNS/users/pf9/code/drt-sans/drtsans/redparms.py", line 1114, in validate_reduction_parameters
    parameters.validate()
  File "/SNS/users/pf9/code/drt-sans/drtsans/redparms.py", line 555, in validate
    cls=self._json_validator, resolver=self._reference_resolver)
  File "/SNS/users/pf9/code/drt-sans/.direnv/python-3.6.8/lib/python3.6/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: Cannot find file /HFIR/CG3/shared/Cycle486/sens_f4829m7p0_TDC_SAC.h5
Failed validating 'dataSource' in schema['properties']['configuration']['properties']['sensitivityMainFileName']:
    {'anyOf': [{'type': 'string'}, {'type': 'null'}],
     'dataSource': 'file',
     'description': 'Path to sensitivity measurement file'}
On instance['configuration']['sensitivityMainFileName']:
    '/HFIR/CG3/shared/Cycle486/sens_f4829m7p0_TDC_SAC.h5'
```

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/612).
