### ISSUE TITLE
[Enabler] Make conda package `mantid` self contained

### ISSUE THREAD

**Issue by glass-ships** [neutrons/drtsans#935]
- [![GitHub issue/pull request detail](https://img.shields.io/github/issues/detail/state/mantidproject/mantid/34913)](https://github.com/mantidproject/mantid/issues/34913)

Description:
===========

The conda package, `mantid` (originally known as `mantid-framework`) provides core computing functionality of `Mantid`.
However, the package itself has some dependency issue which makes it not properly self-contained.

More specifically, when installing the `mantid` package alone in a fresh environment (such as a base container build from miniconda3), the command `from mantid.simpleapi import *` will trigger the following error

- Error_1 (related to dependency on openGL)
NOTE as of 12-14-2022, the first error is no longer present on analysis.
```
Traceback (most recent call last):
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/utils/_utils.py", line 41, in import_mantid_cext
    lib = import_module(modulename.lstrip('.'))
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named '_api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/__init__.py", line 109, in <module>
    from mantid import api as _api  # noqa: F401, E402
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/api/__init__.py", line 20, in <module>
    import_mantid_cext('._api', 'mantid.api', globals())
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/utils/_utils.py", line 46, in import_mantid_cext
    raise ImportError(msg)
ImportError: First import of "._api" failed with "libGL.so.1: cannot open shared object file: No such file or directory". Second import of "_api" failed with "No module named '_api'"
```

- Error_2 (related to import order)

```
>>> from mantid.simpleapi import *
FrameworkManager-[Notice] Welcome to Mantid 6.4.0
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid6.4
Python-[Warning] Failed to load plugin /opt/conda/envs/drtsans-dev/plugins/python/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py.
Error: Traceback (most recent call last):
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/kernel/plugins.py", line 184, in load_from_file
    name, module = load_plugin(filepath)
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/kernel/plugins.py", line 204, in load_plugin
    module = loader.run()
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/kernel/plugins.py", line 49, in run
    return SourceFileLoader(name, pathname).load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1022, in load_module
  File "<frozen importlib._bootstrap_external>", line 847, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/envs/drtsans-dev/plugins/python/algorithms/WorkflowAlgorithms/ISISIndirectDiffractionReduction.py", line 10, in <module>
    from IndirectReductionCommon import load_files, load_file_ranges
  File "/opt/conda/envs/drtsans-dev/scripts/Inelastic/IndirectReductionCommon.py", line 7, in <module>
    from mantid.simpleapi import AppendSpectra, DeleteWorkspace, Load, plotSpectrum
ImportError: cannot import name 'plotSpectrum' from partially initialized module 'mantid.simpleapi' (most likely due to a circular import) (/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/simpleapi.py)

Python-[Warning] Failed to load plugin /opt/conda/envs/drtsans-dev/plugins/python/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py.
Error: Traceback (most recent call last):
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/kernel/plugins.py", line 184, in load_from_file
    name, module = load_plugin(filepath)
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/kernel/plugins.py", line 204, in load_plugin
    module = loader.run()
  File "/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/kernel/plugins.py", line 49, in run
    return SourceFileLoader(name, pathname).load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1022, in load_module
  File "<frozen importlib._bootstrap_external>", line 847, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/conda/envs/drtsans-dev/plugins/python/algorithms/WorkflowAlgorithms/OSIRISDiffractionReduction.py", line 9, in <module>
    from IndirectReductionCommon import load_files
  File "/opt/conda/envs/drtsans-dev/scripts/Inelastic/IndirectReductionCommon.py", line 7, in <module>
    from mantid.simpleapi import AppendSpectra, DeleteWorkspace, Load, plotSpectrum
ImportError: cannot import name 'plotSpectrum' from partially initialized module 'mantid.simpleapi' (most likely due to a circular import) (/opt/conda/envs/drtsans-dev/lib/python3.8/site-packages/mantid/simpleapi.py)

```

Acceptance criteria
-------------------

Improve the `mantid` packaging to resolve the two errors shown above.

The conda recipe for the `mantid` package should include a test section
```yaml
test:
   imports:
     - mantid.simpleapi
```

**Comment by glass-ships** [comment]
This issue was migrated from [code.ornl.gov](https://code.ornl.gov/sns-hfir-scse/sans/sans-backend/-/issues/913).
